version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es
    volumes:
      - esdata:/usr/share/elasticsearch/data
    mem_limit: 1GB
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
    networks:
      - api

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kb
    volumes:
      - kbdata:/usr/share/kibana/data
    ports:
      - '5601:5601'
    networks:
      - api
    depends_on:
      - elasticsearch

  postgres:
    image: postgres:latest
    container_name: pg
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ipss_dev
      POSTGRES_PASSWORD: ipss_pass
      POSTGRES_DB: ipss_dev
    ports:
      - '5432:5432'
    networks:
      - api

volumes:
  esdata:
  kbdata:
  pgdata:

networks:
  api: